### ISSUE TITLE
whay  jib is used for config-service 

### ISSUE THREAD

**Issue by afattahi54** [piomin/sample-spring-microservices-new#86]
The readme file mentioned that

> we need ji for config-service since it contains curl

Can you describe it more please

**Comment by piomin** [comment]
In the `docker-compose.yml` I have the following entry with a health check verification:
```
  config-service:
    image: piomin/config-service:1.1-SNAPSHOT
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/employee/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
``` 
I need it to first verify that `config-server` container is running, before I'll start another containers. Tha't why I need curl inside that container. For example, Paketo Buildpacks Java images don't have curl installed.
